import React from "react"

export const metadata = {
  title: "About Page",
  description: "Generated by create About Page",
}

function AboutPage() {
  return <div>About Page</div>
}

export default AboutPage
