import React from "react"

export const metadata = {
  title: "Post Root Page",
  description: "Generated by create Post Root Page",
}

function PostPage({ params }) {
  return <div>Post Page: {params.post}</div>
}

export default PostPage
