import React from "react"

export const metadata = {
  title: "Blog Page",
  description: "Generated by create Blog Page",
}

function BlogPage({ params }) {
  return <div>Blog Page: {params.blog}</div>
}

export default BlogPage
